language: minimal
dist: trusty
node_js: '10'

branches:
  only:
  - master

services:
  - docker

script:
  - docker build --rm -t toxsickcoder/node-typescript-starter:latest .
  - docker run --rm -it toxsickcoder/node-typescript-starter:latest
